#!/usr/bin/env bash

if [ "$1" != "" ]; then
  ansible-playbook main.yml --user=$(whoami) --ask-become-pass --ask-vault-pass -l $1
else
  ansible-playbook main.yml --user=$(whoami) --ask-become-pass --ask-vault-pass
fi
