# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew colorize colored-man-pages docker git history npm nvm)

source $ZSH/oh-my-zsh.sh

##
# User configuration
##

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR=/usr/bin/nano
else
  export EDITOR=/usr/bin/nano
fi

# Aliases
[ -f "$HOME/.aliases" ] && [ -r "$HOME/.aliases" ] && . "$HOME/.aliases";

# Read and execute .nvmrc
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# Activate ZSH completions
fpath=(/usr/local/share/zsh-completions $fpath)

##
# User functions
##

reset_deps () {
    if [ -f "package.json" ]; then
        echo "Clearing node_modules && jspm_packages and reinstalling..."
        rm -rf node_modules jspm_packages && npm install
    else
        echo "No package.json. Skipping npm install."
    fi

    if [ -f "bower.json" ]; then
        echo "Clearing bower_components and reinstalling..."
        rm -rf bower_components && bower install
    else
        echo "No bower.json. Skipping bower install."
    fi
}
