# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  ansible
  asdf
  aws
  brew
  colorize
  colored-man-pages
  docker
  docker-compose
  git
  gpg-agent
  history
  iterm2
  npm
  terraform
  zsh-autosuggestions
)

# Plugin options
NVM_HOMEBREW=$(brew --prefix nvm)
zstyle ':omz:plugins:nvm' autoload yes

source $ZSH/oh-my-zsh.sh

##
# User configuration
##

# Aliases
[ -f "$HOME/.aliases" ] && [ -r "$HOME/.aliases" ] && . "$HOME/.aliases";

# Activate zsh syntax highlighting
# https://github.com/Homebrew/homebrew-core/blob/master/Formula/zsh-syntax-highlighting.rb
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Activate zsh completions
# https://github.com/Homebrew/homebrew-core/blob/master/Formula/zsh-completions.rb
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  autoload -Uz compinit
  compinit
fi
