---
git_email: "{{ vault_git_email }}"

computer_name: "{{ vault_computer_name }}"

homebrew_packages:
  - ansible
  - asdf
  - git
  - loop
  - pearcleaner
  - speedtest-cli
  - ssh-copy-id
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_casks:
  - 1password
  - arc
  - betterdisplay
  - chatgpt
  - docker-desktop
  - finicky
  - font-fira-code
  - font-jetbrains-mono
  - font-meslo-for-powerline
  - font-sf-mono
  - iterm2
  - maccy
  - obsidian
  - postman
  - signal
  - slack
  - spotify
  - visual-studio-code
  - whatsapp
  - zoom
