---
git_email: "{{ vault_git_email }}"

computer_name: "{{ vault_computer_name }}"

homebrew_packages:
  - awscli
  - curl
  - git
  - httpie
  - speedtest
  - ssh-copy-id
  - wget
  - yarn
  - zsh
  - zsh-completions
  - jq

homebrew_casks:
  - 1password
  - docker
  - dropbox
  - finicky
  - firefox
  - font-fira-code
  - font-meslo-for-powerline
  - google-chrome
  - intellij-idea
  - iterm2
  - lulu
  - notion
  - oversight
  - slack
  - sourcetree
  - spotify
  - visual-studio-code
  - whatsapp
  - zoomus
