---
git_email: "{{ vault_git_email }}"

computer_name: "{{ vault_computer_name }}"

homebrew_packages:
  - awscli
  - aws-sam-cli
  - cfn-lint
  - curl
  - git
  - httpie
  - jq
  - speedtest-cli
  - ssh-copy-id
  - telnet
  - wget
  - yarn
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_casks:
  - 1password
  - docker
  - dropbox
  - finicky
  - firefox
  - font-fira-code
  - font-jetbrains-mono
  - font-meslo-for-powerline
  - google-chrome
  - iterm2
  - notion
  - postman
  - slack
  - sourcetree
  - spotify
  - tweetbot
  - visual-studio-code
  - webstorm
  - whatsapp
  - zoom
