git_email: "{{ vault_git_email }}"
git_signingkey: "{{ vault_git_signingkey }}"

computer_name: "{{ vault_computer_name }}"

ssh_key: hugoduraes-work-mbp

homebrew_taps: []

homebrew_packages:
  - ansible
  - asdf
  - awscli
  - awscli-local
  - direnv
  - git
  - jq
  - pinentry-mac
  - ssh-copy-id
  - terraform
  - wget
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_casks:
  - 1password
  - chatgpt
  - claude
  - claude-code
  - dbeaver-community
  - docker-desktop
  - finicky
  - font-fira-code
  - font-jetbrains-mono
  - font-meslo-for-powerline
  - font-sf-mono
  - granola
  - iterm2
  - loop
  - maccy
  - obsidian
  - pearcleaner
  - postman
  - sbx
  - signal
  - slack
  - spotify
  - visual-studio-code
  - whatsapp
  - zen
  - zoom
