---
- name: close system preferences
  shell: osascript -e 'tell application "System Preferences" to quit'

- name: set computer name
  shell: scutil --set ComputerName "{{ computer_name }}"
    && scutil --set HostName "{{ computer_name }}"
    && scutil --set LocalHostName "{{ computer_name }}"
    && defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "{{ computer_name }}"
  become: true

- name: disable macos dashboard
  shell: defaults write com.apple.dashboard mcx-disabled -bool true

- name: save screenshots to downloads
  shell: defaults write com.apple.screencapture location -string "${HOME}/Downloads"

- name: save screenshots in PNG format
  shell: defaults write com.apple.screencapture type -string "png"

- name: disable shadow in screenshots
  shell: defaults write com.apple.screencapture disable-shadow -bool true

# Dock
- name: minimize windows into their application's icon
  shell: defaults write com.apple.dock minimize-to-application -bool true

- name: automatically hide and show the dock
  shell: defaults write com.apple.dock autohide -bool true

- name: set the icon size of dock items to 28 pixels
  shell: defaults write com.apple.dock tilesize -int 28

- name: set the magnification icon size of dock items to 84 pixels
  shell: defaults write com.apple.dock largesize -int 84

# Keyboard
- name: disable press-and-hold for keys in favor of key repeat
  shell: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

- name: set a blazingly fast keyboard repeat rate
  shell: defaults write NSGlobalDomain KeyRepeat -int 2
    && defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Trackpad
- name: enable tap to click for this user and for the login screen
  shell: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
    && defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    && defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Save panel
- name: expand save panel by default
  shell: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
    && defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

- name: print panel by default
  shell: defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
    && defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Finder
- name: set visibility for hard drives, servers and removable media icons on the desktop
  shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    && defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
    && defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
    && defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

- name: show status bar
  shell: defaults write com.apple.finder ShowStatusBar -bool true

- name: search the current folder by default
  shell: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

- name: enable AirDrop over Ethernet and on unsupported Macs running Lion
  shell: defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

- name: restart dock
  shell: killall Dock
