---
- name: create development folder
  file: path=~/Development state=directory

- name: remove existing dotfiles
  file: path={{ item }} state=absent
  with_items:
    - ~/.aliases
    - ~/.gitconfig
    - ~/.gitignore
    - ~/.zshrc

- name: deploy dotfiles
  template: src=../templates/{{ item }} dest=~/.{{ item }}
  with_items:
    - aliases
    - gitconfig
    - gitignore
    - zshrc

- name: look for finicky dotfile
  stat: path=~/.finicky.js
  register: finicky
  when: inventory_hostname == 'work'

- name: deploy finicky dotfile
  template: src=templates/finicky.js dest=~/.finicky.js
  when: inventory_hostname == 'work' and not finicky.stat.exists

- name: install zsh autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: set zsh as default shell
  shell: chsh -s /bin/zsh
  become: true

- import_tasks: nvm.yml
