- name: create development folder
  file: path=~/Development state=directory

- name: deploy dotfiles
  template: src=../templates/{{ item.src }} dest={{ item.dest }}
  with_items:
    - src: aliases
      dest: ~/.aliases
    - src: asdfrc
      dest: ~/.asdfrc
    - src: gitconfig
      dest: ~/.gitconfig
    - src: gitignore
      dest: ~/.gitignore
    - src: gpg-agent.conf
      dest: ~/.gnupg/gpg-agent.conf
    - src: zshrc
      dest: ~/.zshrc
    - src: ssh_config
      dest: ~/.ssh/config
  notify: restart gpg agent

- name: look for finicky dotfile
  ansible.builtin.stat:
    path: ~/.finicky.ts
  register: st

- name: deploy finicky dotfile
  template: src=templates/finicky.ts dest=~/.finicky.ts
  when: not st.stat.exists

- name: install zsh autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: set zsh as default shell
  shell: chsh -s /bin/zsh
  become: true
