---
- name: look for nvm installation
  stat: path=~/.nvm
  register: nvm

- name: install nvm
  shell: |
    export NVM_DIR="$HOME/.nvm" && (
      git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
      cd "$NVM_DIR"
      git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    ) && \. "$NVM_DIR/nvm.sh"
  when: not nvm.stat.exists

- name: upgrade nvm
  shell: |
    export NVM_DIR="$HOME/.nvm" && (
      cd "$NVM_DIR"
      git fetch --tags origin
      git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    ) && \. "$NVM_DIR/nvm.sh"
  when: nvm.stat.exists

- name: look for installed node default version
  shell: . "$HOME/.nvm/nvm.sh" && nvm list default
  register: default_node_check
  failed_when: default_node_check.rc != 3 # nvm exits with error code 3 when there's no default version installed

- name: install node latest lts and npm
  shell: . "$HOME/.nvm/nvm.sh" && nvm install --lts && nvm install-latest-npm
  when: default_node_check.stdout.find('N/A') != -1

- name: enable npm auto completions
  shell: . "$HOME/.nvm/nvm.sh" && npm completion >> ~/.zshrc
