---
- name: update homebrew
  homebrew: update_homebrew=yes

- name: tap fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: install packages with homebrew
  homebrew: name={{ item }} state=latest
  with_items: "{{ homebrew_packages }}"

- name: install apps with homebrew cask
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ homebrew_casks }}"

- name: cleanup homebrew packages
  command: brew cleanup
