---
- name: update homebrew
  homebrew: update_homebrew=yes

- name: tap fonts
  homebrew_tap: tap=homebrew/cask-fonts state=present

- name: tap aws
  homebrew_tap: tap=aws/tap state=present

- name: install packages with homebrew
  homebrew: name={{ homebrew_packages }} state=latest

- name: install apps with homebrew cask
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ homebrew_casks }}"

- name: cleanup homebrew packages
  command: brew cleanup
