---
- name: update homebrew
  homebrew: update_homebrew=yes

- name: tap fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: install libraries with homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - httpie
    - ssh-copy-id
    - wget
    - zsh
    - zsh-completions
    - jq

- name: install apps with homebrew cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - atom
    - dropbox
    - finicky
    - font-fira-code
    - font-meslo-for-powerline
    - google-chrome
    - hipchat
    - iterm2
    - postman
    - skype
    - slack
    - sourcetree
    - spotify
    - vnc-viewer
    - whatsapp

- name: cleanup homebrew packages
  command: brew cleanup
